version: '3'
services:
  db:
    image: postgres
    env_file: "env.properties"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - mydbdata:/var/lib/postgresql/data

volumes:
  mydbdata: